name: auto update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  # auto update at 1,6,12 o'clock Beijing time
  # check at https://crontab.guru/
  - cron: "0 17,22,4 * * *" 
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - uses: actions/cache@v1
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
      - name: Update tv-guide
        run: |
          pwd
          python get-epg.py
#      - name: Push to built branch
#        uses: Automattic/action-commit-to-branch@master
#        with:
#          branch: 'main'
#          commit_message: '🚀 update tv-guide'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git Commit and Push 
        run: |
          git config core.ignorecase false
          git config --local user.email "frankwuzp@users.noreply.github.com"
          git config --local user.name "frankwuzp"
          git checkout HEAD^ guide.xml
          git pull
          git add .
          git commit -m "🚀 update tv-guide at $(date '+%Y-%m-%d %H:%M:%S')"
          git push
